name: Test & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  greeting: 
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo 'hello from pipeline'
        
  test-utils:
    runs-on: ubuntu-latest 
    steps:
      - name: Clone and checkout the repo 
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run utils tests
        run: npm run test-utils

  test-app: 
    needs: test-utils 
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout the repo
        uses: actions/checkout@v4
      - name: setup postgresql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_news_test
          postgresql password: p4sswOrd
          postgresql user: userface
      - name: install dependencies
        run: npm install
      - name: run integration tests
        run: PGDATABASE=nc_news_test PGPASSWORD=p4sswOrd PGUSER=userface npm run test-app
  ci:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
